server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost/order_db
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
eventuate.database.schema: order_db
management:
  endpoints:
    web:
      exposure:
        include: "*"
# springwolf:
#   docket:
#     base-package: io.eventuate.examples.tram.sagas.ordersandcustomers
#     info:
#       title: ${spring.application.name}
#       version: 1.0.0
#     scanner:
#       async-listener:
#         enabled: false
#     servers:
#       eventuate-producer:
#         protocol: eventuate-outbox
#         host: ${spring.datasource.url}
#       eventuate-consumer:
#         protocol: kafka
#         host: ${eventuatelocal.kafka.bootstrap.servers}
