plugins {
    id 'java-library'
	id 'org.springframework.boot' version '3.5.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

dependencies {
 	implementation(platform("io.eventuate.platform:eventuate-platform-dependencies:$eventuatePlatformVersion"))
    implementation 'io.eventuate.tram.core:eventuate-tram-commands'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

}

